"""empty message

Revision ID: 67640f3f2267
Revises: 
Create Date: 2020-06-19 17:00:38.632212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67640f3f2267'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_game',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('minplayers', sa.Integer(), nullable=True),
    sa.Column('maxplayers', sa.Integer(), nullable=True),
    sa.Column('playingtime', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_game')
    # ### end Alembic commands ###
